### ISSUE TITLE
GitHub Release? (down on Chrome Store)

### ISSUE THREAD

**Issue by lrq3000** [cadomac/fresh-eyes#2]
Would it be possible to build the extension and upload it in a GitHub Release please? The extension is currently down on the Chrome Store, and I understand you may not have time to dedicate to this extension, but if you could just build it it would be super helpful (I was using it all the time on my old computer and I am now reinstalling it on my new one)!

**Comment by lrq3000** [comment]
Thank you so much for all the work you are doing to update to the latest standards! 😃

**Comment by cadomac** [comment]
For sure! It was definitely not compliant with new Chrome Web Store Standards so they wouldn't have allowed me to republish it. It is currently in review to be re-published.

**Comment by lrq3000** [comment]
Awesome! Thank you so much once again, hopefully it will be on the chrome store soon 😃

**Comment by cadomac** [comment]
> Awesome! Thank you so much once again, hopefully it will be on the chrome store soon 😃

It's officially published!

**Comment by lrq3000** [comment]
Awesome! And I see you did lots of supplementary improvement changes too, thank you so much!!!

Do you have a donation link? I'd like to buy you a coffee as a token of my gratitude :-D

**Comment by cadomac** [comment]
Sure! Here's a link: https://ko-fi.com/cadoma

Appreciate it!
